name: Build Image

on: 
  workflow_dispatch:
  push:
    branches:    
      - 'main'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install coreutils p7zip-full qemu-user-static
    - name: Checkout CustomPiOS
      uses: actions/checkout@v2
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS

    - name: Checkout Project Repository
      uses: actions/checkout@v2
      with:
        path: repository
        submodules: true

    - name: Download Raspbian Image
      run: |
        cd repository/src/image
        wget -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf_latest'
    - name: Update CustomPiOS Paths
      run: |
        cd repository/src
        ../../CustomPiOS/src/update-custompios-paths
    
    - name: Force apt mirror to work around intermittent mirror hiccups
      run: |
        echo "OCTOPI_APTMIRROR=http://mirror.us.leaseweb.net/raspbian/raspbian" > repository/src/config.local
    - name: Build Image
      run: |
        sudo modprobe loop
        cd repository/src
        sudo bash -x ./build_dist
    - name: Copy output
      id: copy
      run: |
        source repository/src/config
        NOW=$(date +"%Y-%m-%d-%H%M")
        IMAGE=$NOW-openscan-$DIST_VERSION
        cp repository/src/workspace/*.img $IMAGE.img
        zip -q $IMAGE.img.zip $IMAGE.img
        echo "::set-output name=image::$IMAGE"
    
    - name: Publish relese
      uses: softprops/action-gh-release@v1
      with:
        tag_name:  ${{ steps.copy.outputs.image }}
        files: ${{ steps.copy.outputs.image }}.img.zip

    # artifact upload will take care of zipping for us
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.copy.outputs.image }}
        path: ${{ steps.copy.outputs.image }}.img